### ISSUE TITLE
Flywheel Staging Server - 

### ISSUE THREAD

**Issue by heyadamsilver** [sportstimemachine/theme2016#11]
Client requested and was granted access to the "staging server" beta program.  
Following was relayed:

_You can now activate staging for any of your sites in Flywheel by visiting their 'Advanced' tab within the Flywheel dashboard. Once you do, you should see a new tab called 'Staging (Beta)' that contains all the options for using your staging site. The rest should be pretty straight forward!

Keep in mind, this feature is still in BETA, so let us know immediately if you see any issues, or have any questions at all._

**Eric**. Please setup and push dev to staging.

**Comment by d4mation** [comment]
Staging site is set up at: http://staging.deadpan-cave.flywheelsites.com/

It requires a Username/Password to view, which can be found under your Flywheel Account under the `Flywheel Beta` tab.

From that screen we can easily push changes from Staging->Live as well as from Live->Staging as well 👍
