### ISSUE TITLE
Twitter integration setting

### ISSUE THREAD

**Issue by heyadamsilver** [sportstimemachine/theme2016#12]
From the client: 

"would it be possible to tweak the Twitter widget so it just shows a single entry rather than 5? I'm not sure if the options that are available there but that would allow the page to be a little shorter as it seems to extend as long as those tags go which leaves blank space after the 10 articles per page appear. I thought that may help that issue some."

**Comment by brashrebel** [comment]
Are we simply supposed to make this a "Latest Tweet" widget or would you prefer some option for selecting the number of tweets to show? Doesn't sound the latter would be worth the extra effort but thought I would ask.

**Comment by heyadamsilver** [comment]
checking with client.

**Comment by brashrebel** [comment]
The setting will cost more as it takes just a little extra work. Statically changing the number though is simple enough that we can just do it for you.

**Comment by heyadamsilver** [comment]
update from client:  latest tweet is all that is requested.

**Comment by d4mation** [comment]
All set!
