### ISSUE TITLE
Make current theme a child theme

### ISSUE THREAD

**Issue by brashrebel** [sportstimemachine/theme2016#2]
Since there are updates available for the current theme but modifications made to it, we need to:
1. Make a backup of the site
2. Install an updated version of the theme
3. Define the current theme as a child of the new version
4. Remove any files that are 100% not needed in child theme
5. Address any fatal errors due to duplicate function names
6. Really make sure that no customizations are lost but minimal code exists in child theme

**Comment by d4mation** [comment]
Should be all set. Merged to Master.
