### ISSUE TITLE
Breathe life into dead Twitter widget

### ISSUE THREAD

**Issue by brashrebel** [sportstimemachine/theme2016#4]
The poor old thing is utterly useless now. I believe, but have not confirmed, that it is not functioning because it predates Twitter's major API changes several years ago that now require an app to be registered and authenticated.

We will need to register an app (I think). This should probably be controlled by the client so if Twitter apps don't allow for collaboration, we need to provide detailed instructions for the client to do so. Then we need to use either an existing plugin that creates a Twitter feed widget or make a new one in which case we'll be creating a new repo here.

We should start by looking for well maintained, lightweight Twitter widget plugins and only go custom if we can't find something free and reliable that does the trick.

**Comment by d4mation** [comment]
![image](https://cloud.githubusercontent.com/assets/7770631/16314523/44fff1b6-394c-11e6-9af6-0188d7a99ea2.png)

[First link goes here](https://publish.twitter.com/?url=https%3A%2F%2Ftwitter.com%2FSportsTM#)

The second link 404s.

I've fiddled with https://apps.twitter.com/ slightly in the past. I know that each App ID through them is limited to 10k OAUTH tokens or something like that (Big problem for 3rd Party Twitter Phone Apps), but in this case we'd only be using one so it shouldn't be an issue.

**Comment by d4mation** [comment]
I've got a working solution up on the site, but it currently is using my personal Access Tokens/API Keys for Twitter.

We will want to create a special "App" via https://apps.twitter.com/ for this site specifically.

**Comment by brashrebel** [comment]
@heyadamsilver can you get that for us? An app made for the client and the keys shared (privately) with us?

**Comment by d4mation** [comment]
We need the `Consumer Key`, `Consumer Secret`, `Access Token` and `Access Token Secret`.

**Comment by heyadamsilver** [comment]
Emailing client now for the above mentioned items.

**Comment by heyadamsilver** [comment]
Client provided twitter user / login: 
user: SportsTM 
pw: **REDACTED**

**Comment by d4mation** [comment]
I've edited your comment so the credentials weren't floating out in the open, but I've got them copied down.

[It looks like they need to add a Phone Number (and verify it via Text Message, simply throwing in a fake one won't work) in order to create a Twitter App.](https://support.twitter.com/articles/110250-adding-your-mobile-number-to-your-account-via-web)

**Comment by heyadamsilver** [comment]
Thx for the redacted.   I'll forward the info to the client for the confirm tel

**Comment by heyadamsilver** [comment]
Client has done the cell confirmation.  Can you check now. Thanks.

**Comment by d4mation** [comment]
Twitter App created under their account and the Keys have been added to the site. Thanks!
