### ISSUE TITLE
Implement actual sidebar and widgets

### ISSUE THREAD

**Issue by brashrebel** [sportstimemachine/theme2016#7]
Right now on the site, there's a sidebar with widgets but it is not an actual sidebar with actual widgets. It is just some custom template file. Let's convert everything there to use an actual sidebar like WP is designed to do and create widgets for it. Some of the widgets are being created in other issues so this just includes the ones not already covered.

**Comment by d4mation** [comment]
In [sportstimemachine/theme2016/blob/master/right_sidebar.php#L70](https://github.com/sportstimemachine/theme2016/blob/master/right_sidebar.php#L70) they've got a MailChimp widget included as straight HTML.

Do we have access to their MailChimp account so we can get things rigged up using the official WP Widget?

**Comment by brashrebel** [comment]
Let's open a new issue for that. It would be a nice enhancement for the client to be able to manage the widget from the site. A real widget can allow them to manage the list choice and their API keys and whatnot on their own without calling a dev. But for now, we will drop the HTML into a text widget.

**Comment by d4mation** [comment]
All set. Changes merged into Master.
